// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestConfiguration.proto

package com.mikhail.pravilov.mit.model.protocol;

public final class TestConfigurationProtos {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_testConfiguration_TestConfiguration_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_testConfiguration_TestConfiguration_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\027TestConfiguration.proto\022\021testConfigura" +
                        "tion\"\211\003\n\021TestConfiguration\022f\n\022changing_p" +
                        "arameter\030\001 \001(\01626.testConfiguration.TestC" +
                        "onfiguration.ChangingParameter:\022NUMBER_O" +
                        "F_ELEMENTS\022\032\n\022number_of_requests\030\002 \001(\003\022\032" +
                        "\n\022number_of_elements\030\003 \001(\003\022\031\n\021number_of_" +
                        "clients\030\004 \001(\003\022\035\n\025time_between_requests\030\005" +
                        " \001(\003\022\025\n\rchanging_step\030\006 \001(\003\022\022\n\nfrom_boun" +
                        "d\030\007 \001(\003\022\020\n\010to_bound\030\010 \001(\003\"]\n\021ChangingPar" +
                        "ameter\022\026\n\022NUMBER_OF_ELEMENTS\020\000\022\025\n\021NUMBER" +
                        "_OF_CLIENTS\020\001\022\031\n\025TIME_BETWEEN_REQUESTS\020\002" +
                        "BC\n(com.mikhail.pravilov.mit.model.stati" +
                        "sticB\027TestConfigurationProtos"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_testConfiguration_TestConfiguration_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_testConfiguration_TestConfiguration_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_testConfiguration_TestConfiguration_descriptor,
                new java.lang.String[]{"ChangingParameter", "NumberOfRequests", "NumberOfElements", "NumberOfClients", "TimeBetweenRequests", "ChangingStep", "FromBound", "ToBound",});
    }

    private TestConfigurationProtos() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface TestConfigurationOrBuilder extends
            // @@protoc_insertion_point(interface_extends:testConfiguration.TestConfiguration)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional .testConfiguration.TestConfiguration.ChangingParameter changing_parameter = 1 [default = NUMBER_OF_ELEMENTS];</code>
         */
        boolean hasChangingParameter();

        /**
         * <code>optional .testConfiguration.TestConfiguration.ChangingParameter changing_parameter = 1 [default = NUMBER_OF_ELEMENTS];</code>
         */
        TestConfigurationProtos.TestConfiguration.ChangingParameter getChangingParameter();

        /**
         * <code>optional int64 number_of_requests = 2;</code>
         */
        boolean hasNumberOfRequests();

        /**
         * <code>optional int64 number_of_requests = 2;</code>
         */
        long getNumberOfRequests();

        /**
         * <code>optional int64 number_of_elements = 3;</code>
         */
        boolean hasNumberOfElements();

        /**
         * <code>optional int64 number_of_elements = 3;</code>
         */
        long getNumberOfElements();

        /**
         * <code>optional int64 number_of_clients = 4;</code>
         */
        boolean hasNumberOfClients();

        /**
         * <code>optional int64 number_of_clients = 4;</code>
         */
        long getNumberOfClients();

        /**
         * <code>optional int64 time_between_requests = 5;</code>
         */
        boolean hasTimeBetweenRequests();

        /**
         * <code>optional int64 time_between_requests = 5;</code>
         */
        long getTimeBetweenRequests();

        /**
         * <code>optional int64 changing_step = 6;</code>
         */
        boolean hasChangingStep();

        /**
         * <code>optional int64 changing_step = 6;</code>
         */
        long getChangingStep();

        /**
         * <code>optional int64 from_bound = 7;</code>
         */
        boolean hasFromBound();

        /**
         * <code>optional int64 from_bound = 7;</code>
         */
        long getFromBound();

        /**
         * <code>optional int64 to_bound = 8;</code>
         */
        boolean hasToBound();

        /**
         * <code>optional int64 to_bound = 8;</code>
         */
        long getToBound();
    }

    /**
     * Protobuf type {@code testConfiguration.TestConfiguration}
     */
    public static final class TestConfiguration extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:testConfiguration.TestConfiguration)
            TestConfigurationOrBuilder {
        public static final int CHANGING_PARAMETER_FIELD_NUMBER = 1;
        public static final int NUMBER_OF_REQUESTS_FIELD_NUMBER = 2;
        public static final int NUMBER_OF_ELEMENTS_FIELD_NUMBER = 3;
        public static final int NUMBER_OF_CLIENTS_FIELD_NUMBER = 4;
        public static final int TIME_BETWEEN_REQUESTS_FIELD_NUMBER = 5;
        public static final int CHANGING_STEP_FIELD_NUMBER = 6;
        public static final int FROM_BOUND_FIELD_NUMBER = 7;
        public static final int TO_BOUND_FIELD_NUMBER = 8;
        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<TestConfiguration>
                PARSER = new com.google.protobuf.AbstractParser<TestConfiguration>() {
            public TestConfiguration parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new TestConfiguration(input, extensionRegistry);
            }
        };
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:testConfiguration.TestConfiguration)
        private static final TestConfigurationProtos.TestConfiguration DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new TestConfigurationProtos.TestConfiguration();
        }

        private int bitField0_;
        private int changingParameter_;
        private long numberOfRequests_;
        private long numberOfElements_;
        private long numberOfClients_;
        private long timeBetweenRequests_;
        private long changingStep_;
        private long fromBound_;
        private long toBound_;
        private byte memoizedIsInitialized = -1;

        // Use TestConfiguration.newBuilder() to construct.
        private TestConfiguration(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private TestConfiguration() {
            changingParameter_ = 0;
            numberOfRequests_ = 0L;
            numberOfElements_ = 0L;
            numberOfClients_ = 0L;
            timeBetweenRequests_ = 0L;
            changingStep_ = 0L;
            fromBound_ = 0L;
            toBound_ = 0L;
        }

        private TestConfiguration(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            int rawValue = input.readEnum();
                            TestConfigurationProtos.TestConfiguration.ChangingParameter value = TestConfigurationProtos.TestConfiguration.ChangingParameter.valueOf(rawValue);
                            if (value == null) {
                                unknownFields.mergeVarintField(1, rawValue);
                            } else {
                                bitField0_ |= 0x00000001;
                                changingParameter_ = rawValue;
                            }
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            numberOfRequests_ = input.readInt64();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            numberOfElements_ = input.readInt64();
                            break;
                        }
                        case 32: {
                            bitField0_ |= 0x00000008;
                            numberOfClients_ = input.readInt64();
                            break;
                        }
                        case 40: {
                            bitField0_ |= 0x00000010;
                            timeBetweenRequests_ = input.readInt64();
                            break;
                        }
                        case 48: {
                            bitField0_ |= 0x00000020;
                            changingStep_ = input.readInt64();
                            break;
                        }
                        case 56: {
                            bitField0_ |= 0x00000040;
                            fromBound_ = input.readInt64();
                            break;
                        }
                        case 64: {
                            bitField0_ |= 0x00000080;
                            toBound_ = input.readInt64();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return TestConfigurationProtos.internal_static_testConfiguration_TestConfiguration_descriptor;
        }

        public static TestConfigurationProtos.TestConfiguration parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TestConfigurationProtos.TestConfiguration parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestConfigurationProtos.TestConfiguration parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TestConfigurationProtos.TestConfiguration parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestConfigurationProtos.TestConfiguration parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TestConfigurationProtos.TestConfiguration parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestConfigurationProtos.TestConfiguration parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TestConfigurationProtos.TestConfiguration parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static TestConfigurationProtos.TestConfiguration parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static TestConfigurationProtos.TestConfiguration parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static TestConfigurationProtos.TestConfiguration parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TestConfigurationProtos.TestConfiguration parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(TestConfigurationProtos.TestConfiguration prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static TestConfigurationProtos.TestConfiguration getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<TestConfiguration> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return TestConfigurationProtos.internal_static_testConfiguration_TestConfiguration_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            TestConfigurationProtos.TestConfiguration.class, TestConfigurationProtos.TestConfiguration.Builder.class);
        }

        /**
         * <code>optional .testConfiguration.TestConfiguration.ChangingParameter changing_parameter = 1 [default = NUMBER_OF_ELEMENTS];</code>
         */
        public boolean hasChangingParameter() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional .testConfiguration.TestConfiguration.ChangingParameter changing_parameter = 1 [default = NUMBER_OF_ELEMENTS];</code>
         */
        public TestConfigurationProtos.TestConfiguration.ChangingParameter getChangingParameter() {
            TestConfigurationProtos.TestConfiguration.ChangingParameter result = TestConfigurationProtos.TestConfiguration.ChangingParameter.valueOf(changingParameter_);
            return result == null ? TestConfigurationProtos.TestConfiguration.ChangingParameter.NUMBER_OF_ELEMENTS : result;
        }

        /**
         * <code>optional int64 number_of_requests = 2;</code>
         */
        public boolean hasNumberOfRequests() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional int64 number_of_requests = 2;</code>
         */
        public long getNumberOfRequests() {
            return numberOfRequests_;
        }

        /**
         * <code>optional int64 number_of_elements = 3;</code>
         */
        public boolean hasNumberOfElements() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional int64 number_of_elements = 3;</code>
         */
        public long getNumberOfElements() {
            return numberOfElements_;
        }

        /**
         * <code>optional int64 number_of_clients = 4;</code>
         */
        public boolean hasNumberOfClients() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <code>optional int64 number_of_clients = 4;</code>
         */
        public long getNumberOfClients() {
            return numberOfClients_;
        }

        /**
         * <code>optional int64 time_between_requests = 5;</code>
         */
        public boolean hasTimeBetweenRequests() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        /**
         * <code>optional int64 time_between_requests = 5;</code>
         */
        public long getTimeBetweenRequests() {
            return timeBetweenRequests_;
        }

        /**
         * <code>optional int64 changing_step = 6;</code>
         */
        public boolean hasChangingStep() {
            return ((bitField0_ & 0x00000020) == 0x00000020);
        }

        /**
         * <code>optional int64 changing_step = 6;</code>
         */
        public long getChangingStep() {
            return changingStep_;
        }

        /**
         * <code>optional int64 from_bound = 7;</code>
         */
        public boolean hasFromBound() {
            return ((bitField0_ & 0x00000040) == 0x00000040);
        }

        /**
         * <code>optional int64 from_bound = 7;</code>
         */
        public long getFromBound() {
            return fromBound_;
        }

        /**
         * <code>optional int64 to_bound = 8;</code>
         */
        public boolean hasToBound() {
            return ((bitField0_ & 0x00000080) == 0x00000080);
        }

        /**
         * <code>optional int64 to_bound = 8;</code>
         */
        public long getToBound() {
            return toBound_;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeEnum(1, changingParameter_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt64(2, numberOfRequests_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeInt64(3, numberOfElements_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeInt64(4, numberOfClients_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeInt64(5, timeBetweenRequests_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                output.writeInt64(6, changingStep_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                output.writeInt64(7, fromBound_);
            }
            if (((bitField0_ & 0x00000080) == 0x00000080)) {
                output.writeInt64(8, toBound_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, changingParameter_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(2, numberOfRequests_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(3, numberOfElements_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(4, numberOfClients_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(5, timeBetweenRequests_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(6, changingStep_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(7, fromBound_);
            }
            if (((bitField0_ & 0x00000080) == 0x00000080)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(8, toBound_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof TestConfigurationProtos.TestConfiguration)) {
                return super.equals(obj);
            }
            TestConfigurationProtos.TestConfiguration other = (TestConfigurationProtos.TestConfiguration) obj;

            boolean result = true;
            result = result && (hasChangingParameter() == other.hasChangingParameter());
            if (hasChangingParameter()) {
                result = result && changingParameter_ == other.changingParameter_;
            }
            result = result && (hasNumberOfRequests() == other.hasNumberOfRequests());
            if (hasNumberOfRequests()) {
                result = result && (getNumberOfRequests()
                        == other.getNumberOfRequests());
            }
            result = result && (hasNumberOfElements() == other.hasNumberOfElements());
            if (hasNumberOfElements()) {
                result = result && (getNumberOfElements()
                        == other.getNumberOfElements());
            }
            result = result && (hasNumberOfClients() == other.hasNumberOfClients());
            if (hasNumberOfClients()) {
                result = result && (getNumberOfClients()
                        == other.getNumberOfClients());
            }
            result = result && (hasTimeBetweenRequests() == other.hasTimeBetweenRequests());
            if (hasTimeBetweenRequests()) {
                result = result && (getTimeBetweenRequests()
                        == other.getTimeBetweenRequests());
            }
            result = result && (hasChangingStep() == other.hasChangingStep());
            if (hasChangingStep()) {
                result = result && (getChangingStep()
                        == other.getChangingStep());
            }
            result = result && (hasFromBound() == other.hasFromBound());
            if (hasFromBound()) {
                result = result && (getFromBound()
                        == other.getFromBound());
            }
            result = result && (hasToBound() == other.hasToBound());
            if (hasToBound()) {
                result = result && (getToBound()
                        == other.getToBound());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasChangingParameter()) {
                hash = (37 * hash) + CHANGING_PARAMETER_FIELD_NUMBER;
                hash = (53 * hash) + changingParameter_;
            }
            if (hasNumberOfRequests()) {
                hash = (37 * hash) + NUMBER_OF_REQUESTS_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getNumberOfRequests());
            }
            if (hasNumberOfElements()) {
                hash = (37 * hash) + NUMBER_OF_ELEMENTS_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getNumberOfElements());
            }
            if (hasNumberOfClients()) {
                hash = (37 * hash) + NUMBER_OF_CLIENTS_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getNumberOfClients());
            }
            if (hasTimeBetweenRequests()) {
                hash = (37 * hash) + TIME_BETWEEN_REQUESTS_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getTimeBetweenRequests());
            }
            if (hasChangingStep()) {
                hash = (37 * hash) + CHANGING_STEP_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getChangingStep());
            }
            if (hasFromBound()) {
                hash = (37 * hash) + FROM_BOUND_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getFromBound());
            }
            if (hasToBound()) {
                hash = (37 * hash) + TO_BOUND_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getToBound());
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<TestConfiguration> getParserForType() {
            return PARSER;
        }

        public TestConfigurationProtos.TestConfiguration getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf enum {@code testConfiguration.TestConfiguration.ChangingParameter}
         */
        public enum ChangingParameter
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>NUMBER_OF_ELEMENTS = 0;</code>
             */
            NUMBER_OF_ELEMENTS(0),
            /**
             * <code>NUMBER_OF_CLIENTS = 1;</code>
             */
            NUMBER_OF_CLIENTS(1),
            /**
             * <code>TIME_BETWEEN_REQUESTS = 2;</code>
             */
            TIME_BETWEEN_REQUESTS(2),;

            /**
             * <code>NUMBER_OF_ELEMENTS = 0;</code>
             */
            public static final int NUMBER_OF_ELEMENTS_VALUE = 0;
            /**
             * <code>NUMBER_OF_CLIENTS = 1;</code>
             */
            public static final int NUMBER_OF_CLIENTS_VALUE = 1;
            /**
             * <code>TIME_BETWEEN_REQUESTS = 2;</code>
             */
            public static final int TIME_BETWEEN_REQUESTS_VALUE = 2;
            private static final com.google.protobuf.Internal.EnumLiteMap<
                    ChangingParameter> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<ChangingParameter>() {
                        public ChangingParameter findValueByNumber(int number) {
                            return ChangingParameter.forNumber(number);
                        }
                    };
            private static final ChangingParameter[] VALUES = values();
            private final int value;

            ChangingParameter(int value) {
                this.value = value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @java.lang.Deprecated
            public static ChangingParameter valueOf(int value) {
                return forNumber(value);
            }

            public static ChangingParameter forNumber(int value) {
                switch (value) {
                    case 0:
                        return NUMBER_OF_ELEMENTS;
                    case 1:
                        return NUMBER_OF_CLIENTS;
                    case 2:
                        return TIME_BETWEEN_REQUESTS;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<ChangingParameter>
            internalGetValueMap() {
                return internalValueMap;
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return TestConfigurationProtos.TestConfiguration.getDescriptor().getEnumTypes().get(0);
            }

            public static ChangingParameter valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                return VALUES[desc.getIndex()];
            }

            public final int getNumber() {
                return value;
            }

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(ordinal());
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            // @@protoc_insertion_point(enum_scope:testConfiguration.TestConfiguration.ChangingParameter)
        }

        /**
         * Protobuf type {@code testConfiguration.TestConfiguration}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:testConfiguration.TestConfiguration)
                TestConfigurationProtos.TestConfigurationOrBuilder {
            private int bitField0_;
            private int changingParameter_ = 0;
            private long numberOfRequests_;
            private long numberOfElements_;
            private long numberOfClients_;
            private long timeBetweenRequests_;
            private long changingStep_;
            private long fromBound_;
            private long toBound_;

            // Construct using com.mikhail.pravilov.mit.model.protocol.TestConfigurationProtos.TestConfiguration.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return TestConfigurationProtos.internal_static_testConfiguration_TestConfiguration_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return TestConfigurationProtos.internal_static_testConfiguration_TestConfiguration_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                TestConfigurationProtos.TestConfiguration.class, TestConfigurationProtos.TestConfiguration.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                changingParameter_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                numberOfRequests_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000002);
                numberOfElements_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000004);
                numberOfClients_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000008);
                timeBetweenRequests_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000010);
                changingStep_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000020);
                fromBound_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000040);
                toBound_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000080);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return TestConfigurationProtos.internal_static_testConfiguration_TestConfiguration_descriptor;
            }

            public TestConfigurationProtos.TestConfiguration getDefaultInstanceForType() {
                return TestConfigurationProtos.TestConfiguration.getDefaultInstance();
            }

            public TestConfigurationProtos.TestConfiguration build() {
                TestConfigurationProtos.TestConfiguration result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public TestConfigurationProtos.TestConfiguration buildPartial() {
                TestConfigurationProtos.TestConfiguration result = new TestConfigurationProtos.TestConfiguration(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.changingParameter_ = changingParameter_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.numberOfRequests_ = numberOfRequests_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.numberOfElements_ = numberOfElements_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.numberOfClients_ = numberOfClients_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.timeBetweenRequests_ = timeBetweenRequests_;
                if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                    to_bitField0_ |= 0x00000020;
                }
                result.changingStep_ = changingStep_;
                if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
                    to_bitField0_ |= 0x00000040;
                }
                result.fromBound_ = fromBound_;
                if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
                    to_bitField0_ |= 0x00000080;
                }
                result.toBound_ = toBound_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof TestConfigurationProtos.TestConfiguration) {
                    return mergeFrom((TestConfigurationProtos.TestConfiguration) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(TestConfigurationProtos.TestConfiguration other) {
                if (other == TestConfigurationProtos.TestConfiguration.getDefaultInstance()) return this;
                if (other.hasChangingParameter()) {
                    setChangingParameter(other.getChangingParameter());
                }
                if (other.hasNumberOfRequests()) {
                    setNumberOfRequests(other.getNumberOfRequests());
                }
                if (other.hasNumberOfElements()) {
                    setNumberOfElements(other.getNumberOfElements());
                }
                if (other.hasNumberOfClients()) {
                    setNumberOfClients(other.getNumberOfClients());
                }
                if (other.hasTimeBetweenRequests()) {
                    setTimeBetweenRequests(other.getTimeBetweenRequests());
                }
                if (other.hasChangingStep()) {
                    setChangingStep(other.getChangingStep());
                }
                if (other.hasFromBound()) {
                    setFromBound(other.getFromBound());
                }
                if (other.hasToBound()) {
                    setToBound(other.getToBound());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                TestConfigurationProtos.TestConfiguration parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (TestConfigurationProtos.TestConfiguration) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional .testConfiguration.TestConfiguration.ChangingParameter changing_parameter = 1 [default = NUMBER_OF_ELEMENTS];</code>
             */
            public boolean hasChangingParameter() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional .testConfiguration.TestConfiguration.ChangingParameter changing_parameter = 1 [default = NUMBER_OF_ELEMENTS];</code>
             */
            public TestConfigurationProtos.TestConfiguration.ChangingParameter getChangingParameter() {
                TestConfigurationProtos.TestConfiguration.ChangingParameter result = TestConfigurationProtos.TestConfiguration.ChangingParameter.valueOf(changingParameter_);
                return result == null ? TestConfigurationProtos.TestConfiguration.ChangingParameter.NUMBER_OF_ELEMENTS : result;
            }

            /**
             * <code>optional .testConfiguration.TestConfiguration.ChangingParameter changing_parameter = 1 [default = NUMBER_OF_ELEMENTS];</code>
             */
            public Builder setChangingParameter(TestConfigurationProtos.TestConfiguration.ChangingParameter value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                changingParameter_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>optional .testConfiguration.TestConfiguration.ChangingParameter changing_parameter = 1 [default = NUMBER_OF_ELEMENTS];</code>
             */
            public Builder clearChangingParameter() {
                bitField0_ = (bitField0_ & ~0x00000001);
                changingParameter_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 number_of_requests = 2;</code>
             */
            public boolean hasNumberOfRequests() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional int64 number_of_requests = 2;</code>
             */
            public long getNumberOfRequests() {
                return numberOfRequests_;
            }

            /**
             * <code>optional int64 number_of_requests = 2;</code>
             */
            public Builder setNumberOfRequests(long value) {
                bitField0_ |= 0x00000002;
                numberOfRequests_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 number_of_requests = 2;</code>
             */
            public Builder clearNumberOfRequests() {
                bitField0_ = (bitField0_ & ~0x00000002);
                numberOfRequests_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 number_of_elements = 3;</code>
             */
            public boolean hasNumberOfElements() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional int64 number_of_elements = 3;</code>
             */
            public long getNumberOfElements() {
                return numberOfElements_;
            }

            /**
             * <code>optional int64 number_of_elements = 3;</code>
             */
            public Builder setNumberOfElements(long value) {
                bitField0_ |= 0x00000004;
                numberOfElements_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 number_of_elements = 3;</code>
             */
            public Builder clearNumberOfElements() {
                bitField0_ = (bitField0_ & ~0x00000004);
                numberOfElements_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 number_of_clients = 4;</code>
             */
            public boolean hasNumberOfClients() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <code>optional int64 number_of_clients = 4;</code>
             */
            public long getNumberOfClients() {
                return numberOfClients_;
            }

            /**
             * <code>optional int64 number_of_clients = 4;</code>
             */
            public Builder setNumberOfClients(long value) {
                bitField0_ |= 0x00000008;
                numberOfClients_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 number_of_clients = 4;</code>
             */
            public Builder clearNumberOfClients() {
                bitField0_ = (bitField0_ & ~0x00000008);
                numberOfClients_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 time_between_requests = 5;</code>
             */
            public boolean hasTimeBetweenRequests() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            /**
             * <code>optional int64 time_between_requests = 5;</code>
             */
            public long getTimeBetweenRequests() {
                return timeBetweenRequests_;
            }

            /**
             * <code>optional int64 time_between_requests = 5;</code>
             */
            public Builder setTimeBetweenRequests(long value) {
                bitField0_ |= 0x00000010;
                timeBetweenRequests_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 time_between_requests = 5;</code>
             */
            public Builder clearTimeBetweenRequests() {
                bitField0_ = (bitField0_ & ~0x00000010);
                timeBetweenRequests_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 changing_step = 6;</code>
             */
            public boolean hasChangingStep() {
                return ((bitField0_ & 0x00000020) == 0x00000020);
            }

            /**
             * <code>optional int64 changing_step = 6;</code>
             */
            public long getChangingStep() {
                return changingStep_;
            }

            /**
             * <code>optional int64 changing_step = 6;</code>
             */
            public Builder setChangingStep(long value) {
                bitField0_ |= 0x00000020;
                changingStep_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 changing_step = 6;</code>
             */
            public Builder clearChangingStep() {
                bitField0_ = (bitField0_ & ~0x00000020);
                changingStep_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 from_bound = 7;</code>
             */
            public boolean hasFromBound() {
                return ((bitField0_ & 0x00000040) == 0x00000040);
            }

            /**
             * <code>optional int64 from_bound = 7;</code>
             */
            public long getFromBound() {
                return fromBound_;
            }

            /**
             * <code>optional int64 from_bound = 7;</code>
             */
            public Builder setFromBound(long value) {
                bitField0_ |= 0x00000040;
                fromBound_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 from_bound = 7;</code>
             */
            public Builder clearFromBound() {
                bitField0_ = (bitField0_ & ~0x00000040);
                fromBound_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 to_bound = 8;</code>
             */
            public boolean hasToBound() {
                return ((bitField0_ & 0x00000080) == 0x00000080);
            }

            /**
             * <code>optional int64 to_bound = 8;</code>
             */
            public long getToBound() {
                return toBound_;
            }

            /**
             * <code>optional int64 to_bound = 8;</code>
             */
            public Builder setToBound(long value) {
                bitField0_ |= 0x00000080;
                toBound_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 to_bound = 8;</code>
             */
            public Builder clearToBound() {
                bitField0_ = (bitField0_ & ~0x00000080);
                toBound_ = 0L;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:testConfiguration.TestConfiguration)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
